"""
Deployer Agent.

Responsibility: Take reviewed, approved code and handle deployment steps
(e.g. writing files to disk, calling CI/CD APIs, or triggering cloud deploys).

The orchestrator (n8n) calls POST /agents/deployer with the reviewed code.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional

import httpx

from providers.base import BaseLLMProvider


def _load_system_prompt() -> str:
    prompt_path = Path(__file__).resolve().parent / "prompts" / "system.md"
    if prompt_path.exists():
        return prompt_path.read_text(encoding="utf-8").strip()
    return "You are the Deployer agent. Return deployment readiness and traceable steps."


def _extract_task_id(review: Dict[str, Any]) -> str:
    if isinstance(review.get("task_id"), str):
        return review["task_id"]
    code = review.get("code") if isinstance(review.get("code"), dict) else {}
    objective = str(code.get("objective", ""))
    if "MAS-49" in objective:
        return "MAS-49"
    return ""


def _build_repo_name(review: Dict[str, Any]) -> str:
    code = review.get("code") if isinstance(review.get("code"), dict) else {}
    objective = str(code.get("objective", ""))
    lowered = objective.lower()
    if "create_project" in lowered and "backend" in lowered:
        return "generated-backend-service"
    return "generated-project-repo"


def _create_github_repo(repo_name: str) -> Dict[str, Any]:
    token = os.getenv("GITHUB_TOKEN", "").strip()
    if not token:
        return {
            "attempted": False,
            "created": False,
            "reason": "GITHUB_TOKEN not configured",
            "repo_name": repo_name,
        }

    api_base = os.getenv("GITHUB_API_BASE", "https://api.github.com").strip().rstrip("/")
    owner = os.getenv("GITHUB_OWNER", "").strip()
    create_in_org = os.getenv("GITHUB_CREATE_IN_ORG", "false").strip().lower() == "true"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    payload = {
        "name": repo_name,
        "private": True,
        "auto_init": True,
        "description": "Repository generated by multi-agent deployer",
    }

    if create_in_org and owner:
        endpoint = f"{api_base}/orgs/{owner}/repos"
    else:
        endpoint = f"{api_base}/user/repos"

    with httpx.Client(timeout=30.0) as client:
        response = client.post(endpoint, headers=headers, json=payload)

    if response.status_code in {200, 201}:
        data = response.json()
        return {
            "attempted": True,
            "created": True,
            "repo_name": repo_name,
            "repo_url": data.get("html_url"),
            "api_url": data.get("url"),
            "status_code": response.status_code,
        }

    return {
        "attempted": True,
        "created": False,
        "repo_name": repo_name,
        "status_code": response.status_code,
        "error": response.text,
    }


class DeployerAgent:
    """Stub for the Deployer agent."""

    def __init__(self, llm: BaseLLMProvider) -> None:
        self.llm = llm
        self.system_prompt = _load_system_prompt()

    def run(self, review: Any) -> dict:
        """
        Receive the *review* artefact from the Reviewer and deploy the code.

        TODO: implement actual deployment logic (file writes, API calls, …).

        :param review: Review output produced by the ReviewerAgent.
        :returns: A dict containing the deployment status and any logs.
        """
        if isinstance(review, str):
            try:
                normalized_review = json.loads(review)
            except json.JSONDecodeError:
                normalized_review = {"approved": False, "raw": review}
        else:
            normalized_review = review if isinstance(review, dict) else {"approved": False, "raw": str(review)}

        prompt_review = {
            "approved": bool(normalized_review.get("approved")),
            "summary": normalized_review.get("summary"),
            "findings": normalized_review.get("findings") or [],
        }
        prompt = (
            f"{self.system_prompt}\n\n"
            f"Generate deployment steps for: {prompt_review}\n"
            "Keep output concise and operational."
        )
        response = self.llm.complete(prompt=prompt, temperature=0.2, max_tokens=220)
        approved = bool(normalized_review.get("approved"))
        task_id = _extract_task_id(normalized_review)
        github_repo: Optional[Dict[str, Any]] = None
        if approved and task_id == "MAS-49":
            github_repo = _create_github_repo(_build_repo_name(normalized_review))
        status = "validated" if approved else "blocked"
        deployment_payload = {
            "status": status,
            "ready_for_close": approved,
            "steps": [
                "Revisar estado del pipeline",
                "Confirmar validaciones tecnicas",
                "Autorizar cierre Jira solo con evidencia positiva",
            ],
            "github_repo": github_repo,
            "model_notes": response[:1000],
        }
        return {
            "agent": "deployer",
            "review": normalized_review,
            "deployment": json.dumps(deployment_payload, ensure_ascii=True),
            "status": status,
        }
