"""
Deployer Agent.

Responsibility: Take reviewed, approved code and handle deployment steps
(e.g. writing files to disk, calling CI/CD APIs, or triggering cloud deploys).

The orchestrator (n8n) calls POST /agents/deployer with the reviewed code.
"""

import json
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict, Optional

import httpx

from providers.base import BaseLLMProvider


def _load_system_prompt() -> str:
    prompt_path = Path(__file__).resolve().parent / "prompts" / "system.md"
    if prompt_path.exists():
        return prompt_path.read_text(encoding="utf-8").strip()
    return "You are the Deployer agent. Return deployment readiness and traceable steps."


def _extract_task_id(review: Dict[str, Any]) -> str:
    if isinstance(review.get("task_id"), str):
        return review["task_id"]
    code = review.get("code") if isinstance(review.get("code"), dict) else {}
    objective = str(code.get("objective", ""))
    if "MAS-49" in objective:
        return "MAS-49"
    return ""


def _build_repo_name(review: Dict[str, Any]) -> str:
    code = review.get("code") if isinstance(review.get("code"), dict) else {}
    objective = str(code.get("objective", ""))
    lowered = objective.lower()
    if "create_project" in lowered and "backend" in lowered:
        return "generated-backend-service"
    if "login" in lowered and "crud" in lowered:
        return "generated-login-crud-app"
    return f"generated-app-{hash(objective) % 10000}"


def _create_github_repo(repo_name: str, code_artifact: str = "") -> Dict[str, Any]:
    """Create GitHub repo and commit initial code."""
    token = os.getenv("GITHUB_TOKEN", "").strip()
    if not token:
        return {
            "attempted": False,
            "created": False,
            "reason": "GITHUB_TOKEN not configured",
            "repo_name": repo_name,
            "repo_url": None,
        }

    api_base = os.getenv("GITHUB_API_BASE", "https://api.github.com").strip().rstrip("/")
    owner = os.getenv("GITHUB_OWNER", "").strip()
    create_in_org = os.getenv("GITHUB_CREATE_IN_ORG", "false").strip().lower() == "true"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    payload = {
        "name": repo_name,
        "private": False,
        "auto_init": True,
        "description": "Repository generated by multi-agent deployer",
    }

    if create_in_org and owner:
        endpoint = f"{api_base}/orgs/{owner}/repos"
    else:
        endpoint = f"{api_base}/user/repos"

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(endpoint, headers=headers, json=payload)

        if response.status_code in {200, 201}:
            data = response.json()
            repo_url = data.get("html_url")
            ssh_url = data.get("ssh_url")
            clone_url = data.get("clone_url")

            # If code artifact provided, commit it
            if code_artifact and clone_url:
                _commit_to_repo(repo_url, clone_url, code_artifact, token)

            return {
                "attempted": True,
                "created": True,
                "repo_name": repo_name,
                "repo_url": repo_url,
                "clone_url": clone_url,
                "api_url": data.get("url"),
                "status_code": response.status_code,
            }

        return {
            "attempted": True,
            "created": False,
            "repo_name": repo_name,
            "status_code": response.status_code,
            "error": response.text[:200],
            "repo_url": None,
        }
    except Exception as e:
        return {
            "attempted": True,
            "created": False,
            "repo_name": repo_name,
            "error": str(e),
            "repo_url": None,
        }


def _commit_to_repo(repo_url: str, clone_url: str, code_artifact: str, token: str) -> Dict[str, Any]:
    """Clone repo, commit code, and push."""
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            # Clone repo
            git_clone_url = clone_url.replace("https://", f"https://x-access-token:{token}@")
            result = subprocess.run(
                ["git", "clone", git_clone_url, tmpdir],
                capture_output=True,
                timeout=30,
                text=True,
            )
            if result.returncode != 0:
                return {"success": False, "error": result.stderr}

            # Create main code file
            code_file = Path(tmpdir) / "app.py"
            code_file.write_text(code_artifact, encoding="utf-8")

            # Create requirements.txt stub
            reqs_file = Path(tmpdir) / "requirements.txt"
            reqs_file.write_text("flask==2.3.2\nflask-cors==4.0.0\n", encoding="utf-8")

            # Git add, commit, push
            subprocess.run(["git", "config", "user.name", "Generated Deploy"], cwd=tmpdir, check=False)
            subprocess.run(["git", "config", "user.email", "deploy@generated.local"], cwd=tmpdir, check=False)
            subprocess.run(["git", "add", "."], cwd=tmpdir, check=False)
            result = subprocess.run(
                ["git", "commit", "-m", "Initial app code generated by multi-agent deployer"],
                cwd=tmpdir,
                capture_output=True,
                timeout=30,
                text=True,
            )
            if result.returncode == 0:
                subprocess.run(["git", "push", "-u", "origin", "main"], cwd=tmpdir, check=False)

        return {"success": True}
    except Exception as e:


def _deploy_to_render(repo_url: str, repo_name: str) -> Dict[str, Any]:
    """Deploy repo to Render cloud platform."""
    render_token = os.getenv("RENDER_API_TOKEN", "").strip()
    if not render_token:
        return {
            "attempted": False,
            "deployed": False,
            "reason": "RENDER_API_TOKEN not configured",
            "service_url": None,
        }

    api_base = "https://api.render.com/v1"
    headers = {
        "Authorization": f"Bearer {render_token}",
        "Accept": "application/json",
    }

    # Create service
    payload = {
        "name": repo_name,
        "type": "web_service",
        "repo": repo_url,
        "branch": "main",
        "runtime_id": "python3",
        "buildCommand": "pip install -r requirements.txt",
        "startCommand": "python app.py",
        "plan": "free",
        "envVars": [{"key": "PORT", "value": "8000"}],
    }

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(f"{api_base}/services", headers=headers, json=payload)

        if response.status_code in {200, 201}:
            data = response.json()
            service_id = data.get("id")
            service_url = data.get("serviceDetails", {}).get("url")

            return {
                "attempted": True,
                "deployed": True,
                "service_id": service_id,
                "service_url": service_url,
                "status_code": response.status_code,
            }

        return {
            "attempted": True,
            "deployed": False,
            "status_code": response.status_code,
            "error": response.text[:200],
            "service_url": None,
        }
    except Exception as e:
        return {
            "attempted": True,
            "deployed": False,
            "error": str(e),
            "service_url": None,
        }


class DeployerAgent:
    """Implement real Deployer agent with GitHub + Render integration."""

    def __init__(self, llm: BaseLLMProvider) -> None:
        self.llm = llm
        self.system_prompt = _load_system_prompt()

    def run(self, review: Any) -> dict:
        """
        Receive the *review* artefact from the Reviewer and deploy the code.

        Real implementation: create GitHub repo, commit code, deploy to Render.

        :param review: Review output produced by the ReviewerAgent.
        :returns: A dict containing the deployment status, repo URL, and service URL.
        """
        if isinstance(review, str):
            try:
                normalized_review = json.loads(review)
            except json.JSONDecodeError:
                normalized_review = {"approved": False, "raw": review}
        else:
            normalized_review = review if isinstance(review, dict) else {"approved": False, "raw": str(review)}

        approved = bool(normalized_review.get("approved"))
        task_id = _extract_task_id(normalized_review)

        # Extract code from review
        code_data = normalized_review.get("code", {}) if isinstance(normalized_review.get("code"), dict) else {}
        code_artifact = code_data.get("implementation", "") or code_data.get("code", "")

        github_repo = None
        render_service = None
        deployment_url = None

        # Only deploy if approved
        if approved:
            repo_name = _build_repo_name(normalized_review)

            # Step 1: Create GitHub repo
            github_repo = _create_github_repo(repo_name, code_artifact)

            # Step 2: Deploy to Render if repo was created
            if github_repo.get("created") and github_repo.get("repo_url"):
                render_service = _deploy_to_render(github_repo["repo_url"], repo_name)
                deployment_url = render_service.get("service_url")

        # Generate LLM summary
        prompt_review = {
            "approved": approved,
            "summary": normalized_review.get("summary"),
            "findings": normalized_review.get("findings") or [],
        }
        prompt = (
            f"{self.system_prompt}\n\n"
            f"Deployment result for approved={approved}. "
            f"GitHub repo: {github_repo.get('repo_url') if github_repo else 'pending'}. "
            f"Render service: {deployment_url or 'pending'}.\n"
            "Keep output concise."
        )
        response = self.llm.complete(prompt=prompt, temperature=0.2, max_tokens=220)

        status = "deployed" if deployment_url else ("validated" if approved else "blocked")

        deployment_payload = {
            "status": status,
            "ready_for_close": bool(deployment_url),
            "github_repo": github_repo,
            "render_service": render_service,
            "deployment_url": deployment_url,
            "model_notes": response[:1000],
        }

        return {
            "agent": "deployer",
            "review": normalized_review,
            "deployment": json.dumps(deployment_payload, ensure_ascii=True),
            "status": status,
        }
